// <auto-generated />
using Cafeteria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cafeteria.Migrations
{
    [DbContext(typeof(Press_CoffeContext))]
    [Migration("20210327000808_Iniciodecriacao")]
    partial class Iniciodecriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cafeteria.Models.Cafe", b =>
                {
                    b.Property<int>("Cafeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Descafeinado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4");

                    b.Property<bool>("acucar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("com_leite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Cafeid");

                    b.ToTable("Cafes");
                });
#pragma warning restore 612, 618
        }
    }
}
